[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "text-analyzer"
version = "0.1.0"
description = "A simple text analyzer package"
authors = [
  { name = "Your Name", email = "your@email.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = ["nltk>=3.9", "requests>=2.31",   "beautifulsoup4>=4.12"]

[tool.setuptools.packages.find]
where = ["text_analyzer"]
include = ["TextAnalyzer*"]
